# Generated by Django 4.1 on 2022-09-02 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_financer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_trxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ticker', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='stock_trxn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_financer.user'),
        ),
        migrations.AddField(
            model_name='cash_entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_financer.user'),
        ),
    ]
