# Generated by Django 4.1 on 2022-09-02 03:28

from django.db import migrations
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('personal_financer', '0002_cash_entry_stock_trxn_user_delete_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_entry',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cash_entry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cash_entry',
            name='entries',
            field= JSONField(default=dict),
        ),
    ]
