# Generated by Django 4.1 on 2022-09-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_financer', '0003_remove_cash_entry_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_financer.user')),
            ],
        ),
        migrations.CreateModel(
            name='SingleCurrCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockTrxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_financer.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_trxn',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cash_entry',
        ),
        migrations.DeleteModel(
            name='Stock_trxn',
        ),
    ]
