# Generated by Django 4.1 on 2022-09-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_financer', '0004_cashentry_singlecurrcashentry_stocktrxn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='SingleCurrCashEntry',
        ),
        migrations.RemoveField(
            model_name='stocktrxn',
            name='user',
        ),
        migrations.DeleteModel(
            name='CashEntry',
        ),
        migrations.DeleteModel(
            name='StockTrxn',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
